create database otp_db;
drop table otp_code;
drop table common_otp;
create table common_otp
(
    id           bigint primary key,
    module       varchar(100),
    phone_number varchar(13),
    email        varchar(64),
    retry_count  integer
);

create table otp_code
(
    id            bigint primary key generated by default as identity,
    otp_code      varchar(9) not null,
    text          text,
    common_otp_id bigint     not null,
    created_date  timestamp  not null,
    status        integer,
    constraint common_otp_id_fk foreign key (common_otp_id) references common_otp (id)
);
